import { Geist, Geist_Mono } from "next/font/google";
import { Berkshire_Swash } from "next/font/google";
import "./globals.css";
import HeartCursor from "./HeartCursor";
import Navigation from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const berkshireSwash = Berkshire_Swash({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-berkshire",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${berkshireSwash.variable} antialiased`}
      >
        <Navigation />
        <HeartCursor />
        {children}
      </body>
    </html>
  );
}
